### ISSUE TITLE
Not an issue, just a request

### ISSUE THREAD

**Issue by PlayedIn** [DarkFox/ha-config#1]
Hi,

I wasn't sure if you had seen my question in response to your comment on the list-card site., here:[
List-card issue](https://github.com/custom-cards/list-card/issues/8#issuecomment-467137716)

I was hoping that once I understood your example at the link below and how it related to my issue, I might be able to either modify my node red mqtt publishing flow or modify list-card.js to make it work.  I've been stepping through list-card.js with Chrome dev tools to better understand the format the card currently requires.

If you have time, could you shed some light on the link below?  I'm not that familiar with yaml, but it appears as though you're doing some string manipulation (replacing ' with ") on the payload prior to publishing.  Do you feel that I should do something similar?

https://github.com/DarkFox/ha-config/blob/687791a/packages/integrations/weather.yaml#L123-L128

Thank you,

**Comment by DarkFox** [comment]
@PlayedIn Sorry I didn't see your question for all this time. Did you figure it out? The reason for replacing the single quotes with double quotes, is that converting a python dict to a string, outputs it with single quotes, but JSON requires double quotes. I then add a comma after each line, except if it's the last line.

The whole thing is a massive workaround, to send a valid JSON payload to the attributes endpoint of an MQTT sensor.
